"""add role user

Revision ID: 303160f6f834
Revises: 012e65cd8362
Create Date: 2022-12-07 01:19:03.607863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303160f6f834'
down_revision = '012e65cd8362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), server_default='simple', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
